# Sample .secrets files for a standard installation.

SECRET_KEY = "MY_SECRET_KEY"          # Set this to a random key.
ZOTERO_API_KEY = "MY_ZOTERO_API_KEY"  # Set this to your API key.
ZOTERO_LIBRARY_ID = "9999999"         # Set this to your library id.
ZOTERO_LIBRARY_TYPE = "group"         # Set this to your library type.
